spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DNA_DB_URL:jdbc:mysql://211.38.86.92:3306/dna_db?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:outuser}
    password: ${DB_PASSWORD:password}
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    test-connection: true

auth:
  jwt:
    secret: ${DNA_SECRET_KEY:hellodna}
    exp:
      access: ${DNA_ACCESS_TOKEN_EXP:3600}
      refresh: ${DNA_REFRESH_TOKEN_EXP:15000}

aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY:}
    secret-key: ${AWS_SES_SECRET_KEY:}
